apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart-merico-test.fullname" . }}
  labels:
    {{- include "chart-merico-test.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chart-merico-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-merico-test.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            fsGroup: 2000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
