replicaCount: 1

image:
  repository: ironcore864/go-hello-http
  pullPolicy: IfNotPresent
  tag: "0.0.16"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
