apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-hello-http.fullname" . }}
  labels:
    {{- include "go-hello-http.labels" . | nindent 4 }}
spec:
  # Service type specified in values.yaml
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} # The port that this service will serve on
      targetPort: 8080 # The port on the container to forward to
      protocol: TCP
  selector:
    {{- include "go-hello-http.selectorLabels" . | nindent 4 }}
